Public Module ModMessageText

    Public Const StrCodePereinexistant = "Code père inexistant."
    Public Const StrCodeExist = "Ce code existe déjà."
    Public Const StrValeurExist = "Cette valeur existe déjà"
    Public Const strPremierCaract = " Le code doit commencer par une lettre."
    Public Const strIMP_SUPPRIMER = "Impossible de supprimer cette ligne, elle est utilisé dans un autre module."
    Public Const strValider = "Voulez-vous valider ?"
    Public Const strSupprimer = "Voulez-vous supprimer ?"
    Public Const strChampIntrouvable = "Champ introuvable."
    Public Const strUneSeulLettre = "Vous devrais saisir une seule lettre."
    Public Const strLibelle_Synonyme = "Le synonyme devrait être différent du libellé."
    Public Const strLibelleAn_Synonyme = "Le synonyme devrait être différent du libellé anglais."
    Public Const strLibelle_AutresDenominations = "La dénomination devrait être différente du libellé."
    Public Const strCodeCas = " Le Code CAS doit être sous cette forme [000...0-00-0]."
    Public Const strCodeCasIncorrect = " Le Code CAS est incorrècte."
    Public Const strLibAnglais = "Le libellé anglais existe déjà la liste des synonymes anglais."
    Public Const strClasse = "Merci de remplir au moins une classe."
    Public Const strSpecialite = "Spécialité ne doit pas être vide."
    Public Const strExcipient = "Excipient ne doit pas être vide."
    Public Const strSubac = "Substance active ne doit pas être vide."
    Public Const strChargementOnglet = "Merci de consulter tous les onglets avant de supprimer."
    Public Const strInfo_Obligatoire = "Merci de remplir au moins une entité."
    Public Const strInfo_Obligatoire2 = "Il faut au moins une nature EI clinique ou une nature paraclinique !"
    Public Const strLibelle = "Veuillez saisir un libellé !"
    Public Const strDate = "Veuillez saisir une date de référence !"
    Public Const strReference = "Veuillez saisir une référence !"
    Public Const strDose = "Veuillez saisir une dose seuil !"
    Public Const strPere_Fils = "Un père doit avoir au moins 2 fils !"
    Public Const StrPO_TERRAIN = "Le 1er terrain dans un groupe doit être obligatoirement un terrain physiologique"
    Public Const StrValIncor = "Valeur incorrécte"
    Public Const StrcolIPO_CDF_FREQMAX_CODE_FK2 = "Dans la colonne fréquence maximale, seul les codes commençants par lettre [Z] sont autorisés !"
    Public Const strAlgoPoso = "Voulez vous recalculez les séquences posologies ? "
    Public Const strIndic_Existe = "Nature indication est déjà présente dans la fiche posologie "
    Public Const strIMP_SUPPRIMER_TP = "Impossible de supprimer cette codification, elle est liée à un terrain pére."
    Public Const StrSPobligatoire = "Vous devez choisir une spécialité !"
    Public Const strDeconnecte = "Déconnecté"
    Public Const strConnecte = "Connecté"
    Public Const strConnecter = "Connecter"
    Public Const strConnection = "Connection"
    Public Const strType = "Vous devrais saisir le type de l'url"
    Public Const strTypeExist = "Ce type existe déjà"
    Public Const strChamp = "Vous devrais saisir le nom du champ"
    Public Const strUrl = "Vous devrais saisir un url fixe"
    Public Const strChampUrl = "Ce champ n'existe pas dans la table SP_SPECIALITE"
    Public Const strAlgoDose = "Voulez vous recalculez les doses Min/Max ? "
    Public Const strExport = "Voulez vous exporter ces données en format Excel ? "
    Public Const strAssociation = "Tant que plus d’une substance active existe, vous devez saisir la classe pharmaco-thérapeutique ASSOCIATION"
    Public Const strAlgoDuree = "Voulez vous recalculez les durées Min/Max ? "

    Public Const strFermerFiche = "Veuillez fermer toute les fiche avant de ce deconnecté"

End Module
